project:
  type: website
  output-dir: docs
  
website:
  title: "NY 2024"
  site-url: "https://hl-ny2024.netlify.app/"
  
format:
  html:
    theme: cosmo
    css: style.css
    embed-resources: true
